[[collection]]
type = "art"
title = "The Alchemist"
subtitle = "[Brazilian] Paulo Coelho" # optional
link = "https://www.goodreads.com/book/show/18144590-the-alchemist" # optional
img = "/books/the-alchemist.webp"
content = "A novel that follows the journey of Santiago, a young Andalusian shepherd who dreams of discovering a hidden treasure in Egypt. Guided by omens, a wise alchemist, and his own unwavering faith, Santiago embarks on a life-changing quest of self-discovery. The story explores themes of destiny, personal legend, and the transformative power of following one’s dreams."
footer = "★★★"

[[collection]]
type = "art"
title = "Sapiens: A Brief History of Humankind"
subtitle = "[Israeli] Yuval Noah Harari" # optional
link = "https://www.goodreads.com/book/show/23692271-sapiens"
img = "/books/sapiens.webp"
content = "A fascinating exploration of human history, tracing the evolution of Homo sapiens from ancient times to the modern era. Harari delves into anthropology, biology, and sociology to analyze how humans became the dominant species on Earth."
footer = "★★★★★"

[[collection]]
type = "art"
title = "1984"
subtitle = "[British] George Orwell" # optional
link = "https://www.goodreads.com/book/show/4865.How_to_Win_Friends_Influence_People" # optional
img = "/books/1984.webp"
content = "A dystopian novel set in a totalitarian society ruled by the Party, which has total control over every aspect of people's lives. The story follows Winston Smith, a low-ranking member of the Party, as he becomes disillusioned with the oppressive regime and begins..."
footer = "★★★★"
