[[collection]]
type = "art_simple"
title = "Interstellar"
link = "https://www.imdb.com/title/tt0816692/" 
img = "https://media-cache.cinematerial.com/p/500x/lt3g5lgx/interstellar-movie-poster.jpg?v=1456427301"

[[collection]]
type = "art_simple"
title = "Forrest Gump"
link = "https://www.imdb.com/title/tt0109830/"
img = "https://shorturl.at/nxPj4"
