
[[collection]]
type = "card"
title = "Nexus Info"
subtitle = "Machine Learning Intern"
date = "Oct. 2024"
link = "https://www.nexusinfo.in/"
icon = "https://media.licdn.com/dms/image/v2/D560BAQHbJ98jAoTBWw/company-logo_200_200/company-logo_200_200/0/1705843409324/nexus_software_pvt_ltd_logo?e=2147483647&v=beta&t=WYwmWoTbfn-86oo0zcuuG9Kq3Xzh9CANzWUCFA_4qXA"
content = "Built a simple chatbot for greetings and conversation tracking, also developed a college admission chatbot using PDFs for queries on requirements, deadlines, and processes with Streamlit, Groq, LangChain, and LangChain-Groq, enabling multi-turn interactions and contextual memory."
featured = false  #optional

