[[collection]]
type = "art_simple"
title = "Forrest Gump"
link = "https://www.imdb.com/title/tt0109830/"
img = "/movies/forrest-gump.jpg"

[[collection]]
type = "art_simple"
title = "Interstellar"
link = "https://www.imdb.com/title/tt0816692/" 
img = "/movies/interstellar.webp"

[[collection]]
type = "art_simple"
title = "The Truman Show"
link = "https://www.imdb.com/title/tt0120382/"
img = "/movies/the-truman-show.webp"

[[collection]]
type = "art_simple"
title = "Inception"
link = "https://www.imdb.com/title/tt1375666/"
img = "/movies/inception.webp"

[[collection]]
type = "art_simple"
title = "La La Land"
link = "https://www.imdb.com/title/tt3783958/"
img = "/movies/la-la-land.webp"

[[collection]]
type = "art_simple"
title = "Her"
link = "https://www.imdb.com/title/tt1798709/"
img = "/movies/her.webp"

[[collection]]
type = "art_simple"
title = "Se7en"
link = "https://www.imdb.com/title/tt0114369/"
img = "/movies/se7en.webp"

[[collection]]
type = "art_simple"
title = "Parasite"
link = "https://www.imdb.com/title/tt6751668/"
img = "/movies/parasite.webp"

[[collection]]
type = "art_simple"
title = "千と千尋の神隠し"
link = "https://www.imdb.com/title/tt0245429/"
img = "/movies/spirited-away.webp"

[[collection]]
type = "art_simple"
title = "Thw Wild Robot"
link = "https://www.imdb.com/title/tt29623480/"
img = "/movies/the-wild-robot.webp"
